### ISSUE TITLE
./wbruter --gmail is no longer working

### ISSUE THREAD

**Issue by baraeerriyachy** [wuseman/WBRUTER#10]
the script always says "Sorry, no passwords in wordlist matched gmail current password."
even if the wordlist has the right password 
I think the problem is from this command: 
curl -s -u $mail:$name https://mail.google.com/mail/feed/atom | grep 'xml'

**Comment by wuseman** [comment]
Okay, thanks for letting me know I will take a look immediately

**Comment by wuseman** [comment]
```
curl -sL -u $mail:$name imaps://imap.gmail.com:993/INBOX -v
*   Trying 64.233.161.108:993...
* Connected to imap.gmail.com (64.233.161.108) port 993 (#0)
* found 136 certificates in /etc/ssl/certs/ca-certificates.crt
* found 408 certificates in /etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* SSL connection using TLS1.3 / ECDHE_RSA_AES_256_GCM_SHA384
*   server certificate verification OK
*   server certificate status verification SKIPPED
*   common name: imap.gmail.com (matched)
*   server certificate expiration date OK
*   server certificate activation date OK
*   certificate public key: EC/ECDSA
*   certificate version: #3
*   subject: CN=imap.gmail.com
*   start date: Mon, 06 Jun 2022 09:12:40 GMT
*   expire date: Mon, 29 Aug 2022 09:12:39 GMT
*   issuer: C=US,O=Google Trust Services LLC,CN=GTS CA 1C3
< * OK Gimap ready for requests from xxxxxxxxxx xxxxxxxxxxxxxx
> A001 CAPABILITY
< * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
< A001 OK Thats all she wrote! k8mb722948xxxx
> A002 AUTHENTICATE PLAIN AHd1c2VtYW5AbnIxLxxxxxxx2ZpZWxkMWQ=
< A002 NO [ALERT] Invalid credentials (Failure)
```

Will try upgrade but you can change to that url until I upgrade. 

I get a email from google that they blocked my login; , i need check deeper in this but that works but I dont know how to bypass the block yet.

**Comment by wuseman** [comment]
If login is successful login gets denied and if its wrong credenticals it says invalid credentials on that way we can know if its the right password or not. I will solve it

**Comment by baraeerriyachy** [comment]
thanks for your response.
this command: curl -sL -u gmail:password imaps://imap.gmail.com:993/INBOX -v
also output "Invalid credentials (Failure)" in both cases

**Comment by wuseman** [comment]
Then you are entering wrong credentials, it works to confirm if the password is correct or not and you will see it requests for a one time password if its OK and if its wrong it will say wro

curl -sL -u $(line)  smtps://smtp.gmail.com:465/ -v 2>&1 \
                                    |grep -qo "Application-specific

I didnt update wbruter for a very long time it all started by I was using different bruteforce methods and just merged them all to a one tool to use all, I should take a look on this since most things is probably out of date anyway today so I will take a look for do some new version maybe or upgrading the existing one since mostly of this have changed the way to login...

Whatever, it's not the end of gmail bruteforcing it is just needed to do it another way. 

Its possible to get 3 different answers from gmail via smtp.

1) `< 535-5.7.8 Username and Password not accepted.` - WRONG PASS
2) `< 534-5.7.9 Please log in with your web browser and then try again` - CORRECT PASS

From Googles help desk: 

## I can't sign in to my email client

```
Important: If you can't sign in to your email client, you might see one of these errors:

"Username and password not accepted"
"Invalid credentials"
You're asked to enter your username and password over and over
Step 1: Check your password
If you have these problems or can’t sign in, first check to make sure you’re using the right password.

Step 2: Try these troubleshooting steps
Update your email client to the latest version.
Use an App Password: If you use 2-Step Verification, try signing in with an [App Password](https://support.google.com/accounts/answer/185833).
Important: If you sign in with OAuth, use your regular Google password.
Allow less secure apps: If you don't use 2-Step Verification, you might need to[ allow less secure apps to access your account](https://support.google.com/accounts/answer/6010255).
If you recently changed your Gmail password, you might need to re-enter your Gmail account information or completely repeat your Gmail account setup on your other email client.
The email client's sign-in method might be insecure. Try signing in directly on the Gmail app.

Make sure your mail app isn't set to check for new email too frequently. If your mail app checks for new messages more than once every 10 minutes, the app’s access to your account could be blocked.

So if the client is *NOT* reporting fail or bad credentials as it says, the password is CONFIRMED and that means the password was FOUND. How to login, is another story but this tool only want to validates the password if its OK or NOT OK!

Cheers
```

**Comment by wuseman** [comment]
Ah, it's 4 possible message not 3.

The last one I forgot is:

"Too many simultaneous connections" error

```bash
You can only use 15 IMAP connections per account. If you have many email clients getting messages from Gmail at the same time, you may see the "Too many simultaneous connections" error.

If you use multiple email clients or devices for the same Gmail account, try closing or signing out of some.
```

**Comment by wuseman** [comment]
To be fixed.
