### ISSUE TITLE
cat: /etc/os-release not found

### ISSUE THREAD

**Issue by AlinResources** [wuseman/WBRUTER#6]
Hi i have try to brute force without gui this is the output happens cat: /etc/os-release 
cat: /etc/os-release: No such file or directory
how i fix that?

**Comment by wuseman** [comment]
> Hi i have try to brute force without gui this is the output happens cat: /etc/os-release
> cat: /etc/os-release: No such file or directory
> how i fix that?

Wich linux distro are you getting this message from?

**Comment by AlinResources** [comment]
what is linux distro?I get this message from git bash an program

**Comment by wuseman** [comment]
> what is linux distro?I get this message from git bash an program

Are you trying on a windows machine?

**Comment by kishwordulal1234** [comment]
don't use gui in gui it show error but in cli it doesn't

**Comment by ComeradeCharon** [comment]
Better to use an linux os or rooted phone !!

**Comment by wuseman** [comment]
wbruter has support for various linux distros only. Please use wbruter in a chroot enviroment, virtual machine or via dualboot. This is not a problem for wbruter so I close this issue report, if you have more question in this topic, please re-open the issue and do not create a new issue.

Regards - wuseman
