### ISSUE TITLE
git clone https://github.com/wuseman/WBRUTER cd WBRUTER; ./wbruter --help

### ISSUE THREAD

**Issue by alnaqee** [wuseman/WBRUTER#8]

**Comment by wuseman** [comment]
Sorry for late reply. 

1) Please read the below url about issues for create a more sensible issue report for the develoeprs and your own best: 
https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues 

2) What you are typing as subject is not a wbruter bug, its a @alnaqee  mistake =)

Try: 
    git clone https://github.com/wuseman/WBRUTER cd WBRUTER; ./wbruter

If this was not the issue, please repopen this report with proper info of your problem.

Happy Cracking!

**Comment by Lucian242-rgb** [comment]
i have a big problem , i don't know how to install this site and to open a file in he , cause i can't unlock my phone because i forgot adn i don t wan t to reset him , can you mhelp me
